### ISSUE TITLE
color

### ISSUE THREAD

**Issue by jupoon** [jupoon/sp23-cse110-lab3#2]
## Add: Colors 
Date Created: 4-20-2023
Date Due: 4-23-2023

### Task List
- [x] rgb(r, g, b) or rgba(r, g, b, a)     /* red, green, blue, alpha values */
- [x] #FFF or #FFFFFF                    /* hex codes */
- [x] hsl(h, s, l) or hsla(h, s, l, a)       /* hue, saturation, lightness, alpha values */
- [x] Color name (i.e ‘orange’)
