### ISSUE TITLE
box model

### ISSUE THREAD

**Issue by jupoon** [jupoon/sp23-cse110-lab3#5]
## Add: Box Model
Date Created: 4-20-2023
Date Due: 4-23-2023

 /* configure the containers that holds your HTML content */
(“long” and “short” refer to longhand and shorthand syntax and should give the same results. They’re simply different ways to declare your style rules, use at least one of each syntax. You must use both long and short hand notations for each of the following: margin, padding, border)

### Task List
- [ ] Margin /* spacing between html elements */
    - [ ] Long (margin-top, margin-bottom, margin-left, margin-right)
    - [ ] Short (margin: <top> <right> <bottom> <left>)
    - [ ] Auto margins: margin: auto

- [ ] Padding /* spacing within html elements */
    - [ ] Long (margin-top, margin-bottom, margin-left, margin-right)
    - [ ] Short (margin: <top> <right> <bottom> <left>)
    
- [ ] Borders /* borders around html elements, hint: apply borders before testing out padding and margin to better understand the difference between the two */
    - [ ] border-style
    - [ ] border-color
    - [ ] border-width
    - [ ] border-radius
